// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Order.proto

package go_micro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建订单时
type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Consignmentid        string   `protobuf:"bytes,2,opt,name=consignmentid,proto3" json:"consignmentid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098924d90c513ae, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetConsignmentid() string {
	if m != nil {
		return m.Consignmentid
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type Response struct {
	Consignmentid        string   `protobuf:"bytes,1,opt,name=Consignmentid,proto3" json:"Consignmentid,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Orders               []*Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Err                  string   `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098924d90c513ae, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetConsignmentid() string {
	if m != nil {
		return m.Consignmentid
	}
	return ""
}

func (m *Response) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Response) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//单个订单
type Order struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Createtime           int64    `protobuf:"varint,4,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098924d90c513ae, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.order.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.order.Response")
	proto.RegisterType((*Order)(nil), "go.micro.srv.order.Order")
}

func init() { proto.RegisterFile("Order.proto", fileDescriptor_a098924d90c513ae) }

var fileDescriptor_a098924d90c513ae = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xdd, 0x4a, 0x33, 0x31,
	0x10, 0xfd, 0xb6, 0xe9, 0x6e, 0x3f, 0xa7, 0x08, 0x32, 0x88, 0xc6, 0x1f, 0xa4, 0x2c, 0x5e, 0x78,
	0x15, 0xb1, 0x3e, 0x81, 0xd4, 0x22, 0x5e, 0x09, 0x79, 0x01, 0xa9, 0xbb, 0x43, 0x09, 0x74, 0x37,
	0x6b, 0x92, 0xf5, 0x01, 0x7c, 0x07, 0x5f, 0xc7, 0x67, 0x93, 0x24, 0x2b, 0x74, 0x71, 0xeb, 0x8d,
	0x77, 0x33, 0xe7, 0x4c, 0x4e, 0xce, 0x9c, 0x04, 0xa6, 0x4f, 0xa6, 0x24, 0x23, 0x1a, 0xa3, 0x9d,
	0x46, 0x5c, 0x6b, 0x51, 0xa9, 0xc2, 0x68, 0x61, 0xcd, 0x9b, 0xd0, 0x9e, 0xc9, 0x0d, 0x4c, 0x24,
	0xbd, 0xb6, 0x64, 0x1d, 0x1e, 0xc3, 0xa4, 0xb5, 0x64, 0x9e, 0x55, 0xc9, 0x93, 0x59, 0x72, 0xb5,
	0x27, 0x33, 0xdf, 0x3e, 0x96, 0x78, 0x09, 0xfb, 0x85, 0xae, 0xad, 0x5a, 0xd7, 0x15, 0xd5, 0x4e,
	0x95, 0x7c, 0x14, 0xe8, 0x3e, 0x88, 0x08, 0xe3, 0x7a, 0x55, 0x11, 0x67, 0x81, 0x0c, 0x35, 0x1e,
	0x42, 0xda, 0x18, 0x55, 0x10, 0x1f, 0x07, 0x30, 0x36, 0xf9, 0x67, 0x02, 0xff, 0x25, 0xd9, 0x46,
	0xd7, 0x96, 0xbc, 0xf8, 0xa2, 0x27, 0x1e, 0xef, 0xee, 0x83, 0x78, 0x0d, 0x69, 0xf0, 0x1b, 0xae,
	0x9e, 0xce, 0x4f, 0xc4, 0xcf, 0x55, 0x44, 0x58, 0x55, 0xc6, 0x39, 0xbc, 0x81, 0x2c, 0x14, 0x96,
	0xb3, 0x19, 0xfb, 0xfd, 0x44, 0x37, 0x88, 0x07, 0xc0, 0xc8, 0x98, 0xce, 0xaa, 0x2f, 0xf1, 0x08,
	0x32, 0xeb, 0x56, 0xae, 0xb5, 0x3c, 0x8d, 0x81, 0xc4, 0x2e, 0x7f, 0x4f, 0x20, 0x0d, 0x67, 0x77,
	0x67, 0xf6, 0x9d, 0xc6, 0x68, 0x28, 0x0d, 0xb6, 0x95, 0x06, 0x5e, 0x00, 0x14, 0x86, 0x56, 0x8e,
	0x9c, 0xaa, 0x62, 0x50, 0x4c, 0x6e, 0x21, 0xbb, 0x4c, 0xcc, 0x3f, 0xbc, 0x09, 0x79, 0xbf, 0x94,
	0xb8, 0x84, 0x6c, 0x11, 0xe6, 0xf1, 0x6c, 0x68, 0xcb, 0xee, 0x7d, 0x4f, 0xcf, 0x87, 0xc9, 0xf8,
	0x0e, 0xf9, 0x3f, 0x2f, 0xf3, 0x40, 0xee, 0x6e, 0xb3, 0xf9, 0x93, 0xcc, 0x4b, 0x16, 0x3e, 0xdb,
	0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x65, 0x87, 0x45, 0x7b, 0x02, 0x00, 0x00,
}
